//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactEntrepriseToCoordinator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactEntrepriseToCoordinator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.ContactEntrepriseToCoordinator", typeof(ContactEntrepriseToCoordinator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} s&apos;est inscrit sur le site..
        /// </summary>
        internal static string CreateContactEnterprise {
            get {
                return ResourceManager.GetString("CreateContactEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un employé s&apos;est inscrit sur le site Stagio.
        /// </summary>
        internal static string CreateContactEnterpriseTitle {
            get {
                return ResourceManager.GetString("CreateContactEnterpriseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entreprise {0} a modifié le stage:  &lt;a href=&quot;../../Stage/Details/{1}&quot;&gt;{2}&lt;/a&gt;.
        /// </summary>
        internal static string EditStageMessage {
            get {
                return ResourceManager.GetString("EditStageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une entreprise a modifié un stage.
        /// </summary>
        internal static string EditStageTitle {
            get {
                return ResourceManager.GetString("EditStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} est intéressé par la candidature de {1} {2}.
        /// </summary>
        internal static string InterestedBy {
            get {
                return ResourceManager.GetString("InterestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une entreprise est intéressé par la candidature d&apos;un étudiant.
        /// </summary>
        internal static string InterestedByTitle {
            get {
                return ResourceManager.GetString("InterestedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt;Cliquer ici pour voir les détails de ce stage&lt;/a&gt;.
        /// </summary>
        internal static string NewStageEndLink {
            get {
                return ResourceManager.GetString("NewStageEndLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;a href=&quot;http://jenkins.cegep-ste-foy.qc.ca/thomarelau/Stage/Details/.
        /// </summary>
        internal static string NewStageLink {
            get {
                return ResourceManager.GetString("NewStageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez l&apos;approuver pour qu&apos;il soit visible pour les étudiants..
        /// </summary>
        internal static string NewStageMessage {
            get {
                return ResourceManager.GetString("NewStageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un nouveau stage est en attente d&apos;approbation.
        /// </summary>
        internal static string NewStageTitle {
            get {
                return ResourceManager.GetString("NewStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas intéressé par la candidature de {1} {2}.
        /// </summary>
        internal static string NotInterestedBy {
            get {
                return ResourceManager.GetString("NotInterestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une entreprise n&apos;est pas intéressé par la candidature d&apos;un étudiant.
        /// </summary>
        internal static string NotInterestedByTitle {
            get {
                return ResourceManager.GetString("NotInterestedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a retiré le stage &lt;a href=&quot;../../Stage/Details/{1}&quot;&gt;{2}&lt;/a&gt;.
        /// </summary>
        internal static string RemoveStage {
            get {
                return ResourceManager.GetString("RemoveStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une entreprise à retiré une de ses offres de stages.
        /// </summary>
        internal static string RemoveStageTitle {
            get {
                return ResourceManager.GetString("RemoveStageTitle", resourceCulture);
            }
        }
    }
}
