//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactEnterpriseToStudent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactEnterpriseToStudent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.ContactEnterpriseToStudent", typeof(ContactEnterpriseToStudent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  a modifié le stage suivant: .
        /// </summary>
        internal static string EditStageMessage {
            get {
                return ResourceManager.GetString("EditStageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une entreprise a modifié son offre de stage.
        /// </summary>
        internal static string EditStageTitle {
            get {
                return ResourceManager.GetString("EditStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entreprise {0} a ajouté ce stage: &lt;a href=&quot;../../Stage/ViewStageInfo/{1}&quot;&gt;{2}&lt;/a&gt; .
        /// </summary>
        internal static string NewStageMessage {
            get {
                return ResourceManager.GetString("NewStageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un nouveau stage est disponible.
        /// </summary>
        internal static string NewStageTitle {
            get {
                return ResourceManager.GetString("NewStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a retiré le stage {1}&lt;/a&gt;.
        /// </summary>
        internal static string RemoveStage {
            get {
                return ResourceManager.GetString("RemoveStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une entreprise à retiré une de ses offres de stages.
        /// </summary>
        internal static string RemoveStageTitle {
            get {
                return ResourceManager.GetString("RemoveStageTitle", resourceCulture);
            }
        }
    }
}
