//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification
{


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactEntrepriseToCoordinator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactEntrepriseToCoordinator() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.ContactEntrepriseToCoordinator", typeof(ContactEntrepriseToCoordinator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à s&apos;est inscrit sur le site..
        /// </summary>
        internal static string CreateContactEnterprise {
            get {
                return ResourceManager.GetString("CreateContactEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un employé s&apos;est inscrit sur le site Stagio.
        /// </summary>
        internal static string CreateContactEnterpriseTitle {
            get {
                return ResourceManager.GetString("CreateContactEnterpriseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a modifié le stage.
        /// </summary>
        internal static string EditStageMessage {
            get {
                return ResourceManager.GetString("EditStageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une entreprise a modifié un stage.
        /// </summary>
        internal static string EditStageTitle {
            get {
                return ResourceManager.GetString("EditStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à est  intéressé par la candidature de.
        /// </summary>
        internal static string InterestedBy {
            get {
                return ResourceManager.GetString("InterestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une entreprise est intéressé par la candidature d&apos;un étudiant.
        /// </summary>
        internal static string InterestedByTitle {
            get {
                return ResourceManager.GetString("InterestedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt;Cliquer ici pour voir les détails de ce stage&lt;/a&gt;.
        /// </summary>
        internal static string NewStageEndLink {
            get {
                return ResourceManager.GetString("NewStageEndLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;a href=&quot;../../Stage/Details/.
        /// </summary>
        internal static string NewStageLink {
            get {
                return ResourceManager.GetString("NewStageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez l&apos;approuver pour qu&apos;il soit visible pour les étudiants..
        /// </summary>
        internal static string NewStageMessage {
            get {
                return ResourceManager.GetString("NewStageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un nouveau stage est en attente d&apos;approbation.
        /// </summary>
        internal static string NewStageTitle {
            get {
                return ResourceManager.GetString("NewStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;est pas intéressé par la candidature de.
        /// </summary>
        internal static string NotInterestedBy {
            get {
                return ResourceManager.GetString("NotInterestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une entreprise n&apos;est pas intéressé par la candidature d&apos;un étudiant.
        /// </summary>
        internal static string NotInterestedByTitle {
            get {
                return ResourceManager.GetString("NotInterestedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a retiré le stage.
        /// </summary>
        internal static string RemoveStage {
            get {
                return ResourceManager.GetString("RemoveStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une entreprise à retiré une de ses offres de stages.
        /// </summary>
        internal static string RemoveStageTitle {
            get {
                return ResourceManager.GetString("RemoveStageTitle", resourceCulture);
            }
        }
    }
}
