//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoordinatorToContactEnterprise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoordinatorToContactEnterprise() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.CoordinatorToContactEnterprise", typeof(CoordinatorToContactEnterprise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre offre de stage est maintenant visible pour les étudiants..
        /// </summary>
        internal static string StageAcceptedMessage {
            get {
                return ResourceManager.GetString("StageAcceptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre offre de stage a été acceptée par un coordonnateur.
        /// </summary>
        internal static string StageAcceptedTitle {
            get {
                return ResourceManager.GetString("StageAcceptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une convention de stage pour le stage {0} a été créée. Vous pouvez maintenant la &lt;a href=&quot;../../StageAgreement/List&quot;&gt;signer&lt;/a&gt; ..
        /// </summary>
        internal static string StageAgreementCreatedMessage {
            get {
                return ResourceManager.GetString("StageAgreementCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une convention de stage a été créée.
        /// </summary>
        internal static string StageAgreementCreatedTitle {
            get {
                return ResourceManager.GetString("StageAgreementCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} a signé la convention de stage pour le stage {2}. &lt;a href=&quot;../../StageAgreement/Edit?idStageAgreement={3}&quot;&gt;Détails&lt;/a&gt;.
        /// </summary>
        internal static string StageAgreementSignedMessage {
            get {
                return ResourceManager.GetString("StageAgreementSignedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un utilisateur a signé une convention de stage vous concernant.
        /// </summary>
        internal static string StageAgreementSignedTitle {
            get {
                return ResourceManager.GetString("StageAgreementSignedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre offre de stage a été refusée. Vous pouvez la modifier et elle devra être approuvée de nouveau..
        /// </summary>
        internal static string StageRefusedMessage {
            get {
                return ResourceManager.GetString("StageRefusedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre offre de stage a été refusée par un coordonnateur.
        /// </summary>
        internal static string StageRefusedTitle {
            get {
                return ResourceManager.GetString("StageRefusedTitle", resourceCulture);
            }
        }
    }
}
