//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudentToCoordinator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentToCoordinator() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.StudentToCoordinator", typeof(StudentToCoordinator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} a postulé pour ce stage: &lt;a href=&quot;../../Stage/Details/{2}&quot;&gt;{3}&lt;/a&gt;.
        /// </summary>
        internal static string ApplyMessage {
            get {
                return ResourceManager.GetString("ApplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un étudiant a postulé pour un stage.
        /// </summary>
        internal static string ApplyTilte {
            get {
                return ResourceManager.GetString("ApplyTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} a une entrevue le {2} pour un stage chez {3}.
        /// </summary>
        internal static string CreateInterview {
            get {
                return ResourceManager.GetString("CreateInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un étudiant a inscrit une date d&apos;entrevue pour un stage.
        /// </summary>
        internal static string CreateInterviewTitle {
            get {
                return ResourceManager.GetString("CreateInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} s&apos;est inscrit sur le site..
        /// </summary>
        internal static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un étudiant s&apos;est inscrit sur le site Stagio.
        /// </summary>
        internal static string CreateStudentTitle {
            get {
                return ResourceManager.GetString("CreateStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;entrevue de {0} {1} sera le {2} pour le stage {3} de {4}..
        /// </summary>
        internal static string EditDateInterviewMessage {
            get {
                return ResourceManager.GetString("EditDateInterviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un étudiant a changé une date d&apos;entrevue.
        /// </summary>
        internal static string EditDateInterviewTitle {
            get {
                return ResourceManager.GetString("EditDateInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} s&apos;est présenté à son entrevue chez {2} le {3}..
        /// </summary>
        internal static string EditInterviewMessage {
            get {
                return ResourceManager.GetString("EditInterviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un étudiant s&apos;est présenté à une entrevue.
        /// </summary>
        internal static string EditInterviewTitle {
            get {
                return ResourceManager.GetString("EditInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a retiré sa candidature pour le stage: {1}.
        /// </summary>
        internal static string RemoveApplyMessage {
            get {
                return ResourceManager.GetString("RemoveApplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un étudiant a retiré sa candidature à un stage.
        /// </summary>
        internal static string RemoveApplyTitle {
            get {
                return ResourceManager.GetString("RemoveApplyTitle", resourceCulture);
            }
        }
    }
}
