//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudentToCoordinator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentToCoordinator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.StudentToCoordinator", typeof(StudentToCoordinator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a postulé pour ce stage: &lt;a href=&quot;../../Stage/Details/{2}&quot;&gt;{3}&lt;/a&gt;.
        /// </summary>
        internal static string ApplyMessage {
            get {
                return ResourceManager.GetString("ApplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant a postulé pour un stage.
        /// </summary>
        internal static string ApplyTilte {
            get {
                return ResourceManager.GetString("ApplyTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a une entrevue le {2} pour un stage chez {3}.
        /// </summary>
        internal static string CreateInterview {
            get {
                return ResourceManager.GetString("CreateInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant a inscrit une date d&apos;entrevue pour un stage.
        /// </summary>
        internal static string CreateInterviewTitle {
            get {
                return ResourceManager.GetString("CreateInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} s&apos;est inscrit sur le site..
        /// </summary>
        internal static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant s&apos;est inscrit sur le site Stagio.
        /// </summary>
        internal static string CreateStudentTitle {
            get {
                return ResourceManager.GetString("CreateStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entrevue de {0} {1} sera le {2} pour le stage {3} de {4}..
        /// </summary>
        internal static string EditDateInterviewMessage {
            get {
                return ResourceManager.GetString("EditDateInterviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant a changé une date d&apos;entrevue.
        /// </summary>
        internal static string EditDateInterviewTitle {
            get {
                return ResourceManager.GetString("EditDateInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} s&apos;est présenté à son entrevue chez {2} le {3}..
        /// </summary>
        internal static string EditInterviewMessage {
            get {
                return ResourceManager.GetString("EditInterviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant s&apos;est présenté à une entrevue.
        /// </summary>
        internal static string EditInterviewTitle {
            get {
                return ResourceManager.GetString("EditInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a retiré sa candidature pour le stage: {1}.
        /// </summary>
        internal static string RemoveApplyMessage {
            get {
                return ResourceManager.GetString("RemoveApplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant à retiré sa candidature à un stage.
        /// </summary>
        internal static string RemoveApplyTitle {
            get {
                return ResourceManager.GetString("RemoveApplyTitle", resourceCulture);
            }
        }
    }
}
