//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Notification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StudentToCoordinator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentToCoordinator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Notification.StudentToCoordinator", typeof(StudentToCoordinator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a une entrevue le.
        /// </summary>
        internal static string CreateInterviewPart1 {
            get {
                return ResourceManager.GetString("CreateInterviewPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pour un stage chez.
        /// </summary>
        internal static string CreateInterviewPart2 {
            get {
                return ResourceManager.GetString("CreateInterviewPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant a inscrit une date d&apos;entrevue pour un stage.
        /// </summary>
        internal static string CreateInterviewTitle {
            get {
                return ResourceManager.GetString("CreateInterviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s&apos;est inscrit sur le site..
        /// </summary>
        internal static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant s&apos;est inscrit sur le site Stagio.
        /// </summary>
        internal static string CreateStudentTitle {
            get {
                return ResourceManager.GetString("CreateStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a retiré sa candidature pour le stage: {1}.
        /// </summary>
        internal static string RemoveApplyMessage {
            get {
                return ResourceManager.GetString("RemoveApplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un étudiant à retiré sa candidature à un stage.
        /// </summary>
        internal static string RemoveApplyTitle {
            get {
                return ResourceManager.GetString("RemoveApplyTitle", resourceCulture);
            }
        }
    }
}
