//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Shared {
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlashMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlashMessageResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Shared.FlashMessageResources", typeof(FlashMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout avec succès.
        /// </summary>
        internal static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez déjà postulé sur ce stage.
        /// </summary>
        internal static string AlreadyApplied {
            get {
                return ResourceManager.GetString("AlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postulation retirée.
        /// </summary>
        internal static string ApplyDelete {
            get {
                return ResourceManager.GetString("ApplyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La postulation n&apos;existe pas.
        /// </summary>
        internal static string ApplyNotExist {
            get {
                return ResourceManager.GetString("ApplyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postulation réactivée.
        /// </summary>
        internal static string ApplyReactivate {
            get {
                return ResourceManager.GetString("ApplyReactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création du profil réussi.
        /// </summary>
        internal static string CreateAccountSuccess {
            get {
                return ResourceManager.GetString("CreateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brouillon effacé.
        /// </summary>
        internal static string DraftDelete {
            get {
                return ResourceManager.GetString("DraftDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification avec succès.
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreurs dans la page.
        /// </summary>
        internal static string ErrorsOnPage {
            get {
                return ResourceManager.GetString("ErrorsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez déjà inscrit une date d&apos;entrevue pour ce stage..
        /// </summary>
        internal static string InterviewDateAlreadyExist {
            get {
                return ResourceManager.GetString("InterviewDateAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;entrevue que vous tentez de visualiser n&apos;existe pas!.
        /// </summary>
        internal static string InterviewNotExist {
            get {
                return ResourceManager.GetString("InterviewNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier invalide, le fichier doit être un fichier Word ou PDF.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invitation envoyée.
        /// </summary>
        internal static string InvitationSend {
            get {
                return ResourceManager.GetString("InvitationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas les accès pour visualiser cette postulation.
        /// </summary>
        internal static string NotAccessApply {
            get {
                return ResourceManager.GetString("NotAccessApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas les accès pour visualiser cette entrevue.
        /// </summary>
        internal static string NotAccessInterview {
            get {
                return ResourceManager.GetString("NotAccessInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas accès à ce stage.
        /// </summary>
        internal static string NotAccessStage {
            get {
                return ResourceManager.GetString("NotAccessStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas enlever ce stage.
        /// </summary>
        internal static string NotAccessStageRemove {
            get {
                return ResourceManager.GetString("NotAccessStageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réactivation réussie.
        /// </summary>
        internal static string ReactivateSuccess {
            get {
                return ResourceManager.GetString("ReactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accès au site est fermer pour les étudiants et les contacts entreprises.
        /// </summary>
        internal static string SiteClosed {
            get {
                return ResourceManager.GetString("SiteClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le site est pas encore ouvert.
        /// </summary>
        internal static string SiteNotOpen {
            get {
                return ResourceManager.GetString("SiteNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage désactivé.
        /// </summary>
        internal static string StageDesactivated {
            get {
                return ResourceManager.GetString("StageDesactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stage réactivé.
        /// </summary>
        internal static string StageReactivated {
            get {
                return ResourceManager.GetString("StageReactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stage en attente d&apos;approbation.
        /// </summary>
        internal static string StageWaiting {
            get {
                return ResourceManager.GetString("StageWaiting", resourceCulture);
            }
        }
    }
}
