//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlashMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlashMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Shared.FlashMessageResources", typeof(FlashMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout avec succès.
        /// </summary>
        internal static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà postulé sur ce stage.
        /// </summary>
        internal static string AlreadyApplied {
            get {
                return ResourceManager.GetString("AlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postulation retirée.
        /// </summary>
        internal static string ApplyDelete {
            get {
                return ResourceManager.GetString("ApplyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La postulation n&apos;existe pas.
        /// </summary>
        internal static string ApplyNotExist {
            get {
                return ResourceManager.GetString("ApplyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postulation réactivée.
        /// </summary>
        internal static string ApplyReactivate {
            get {
                return ResourceManager.GetString("ApplyReactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création du profil réussi.
        /// </summary>
        internal static string CreateAccountSuccess {
            get {
                return ResourceManager.GetString("CreateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brouillon effacé.
        /// </summary>
        internal static string DraftDelete {
            get {
                return ResourceManager.GetString("DraftDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification avec succès.
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurs dans la page.
        /// </summary>
        internal static string ErrorsOnPage {
            get {
                return ResourceManager.GetString("ErrorsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà inscrit une date d&apos;entrevue pour ce stage..
        /// </summary>
        internal static string InterviewDateAlreadyExist {
            get {
                return ResourceManager.GetString("InterviewDateAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entrevue que vous tentez de visualiser n&apos;existe pas!.
        /// </summary>
        internal static string InterviewNotExist {
            get {
                return ResourceManager.GetString("InterviewNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier invalide, le fichier doit être un fichier Word ou PDF.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation envoyée.
        /// </summary>
        internal static string InvitationSend {
            get {
                return ResourceManager.GetString("InvitationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas les accès pour visualiser cette postulation.
        /// </summary>
        internal static string NotAccessApply {
            get {
                return ResourceManager.GetString("NotAccessApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas les accès pour visualiser cette entrevue.
        /// </summary>
        internal static string NotAccessInterview {
            get {
                return ResourceManager.GetString("NotAccessInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas accès à ce stage.
        /// </summary>
        internal static string NotAccessStage {
            get {
                return ResourceManager.GetString("NotAccessStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas enlever ce stage.
        /// </summary>
        internal static string NotAccessStageRemove {
            get {
                return ResourceManager.GetString("NotAccessStageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réactivation réussi.
        /// </summary>
        internal static string ReactivateSuccess {
            get {
                return ResourceManager.GetString("ReactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accès au site est fermer pour les étudiants et les contacts entreprises.
        /// </summary>
        internal static string SiteClosed {
            get {
                return ResourceManager.GetString("SiteClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le site est pas encore ouvert.
        /// </summary>
        internal static string SiteNotOpen {
            get {
                return ResourceManager.GetString("SiteNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage désactivé.
        /// </summary>
        internal static string StageDesactivated {
            get {
                return ResourceManager.GetString("StageDesactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage réactivé.
        /// </summary>
        internal static string StageReactivated {
            get {
                return ResourceManager.GetString("StageReactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage en attente d&apos;approbation.
        /// </summary>
        internal static string StageWaiting {
            get {
                return ResourceManager.GetString("StageWaiting", resourceCulture);
            }
        }
    }
}
