//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stagio.Web.Module.Strings.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoordinatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoordinatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stagio.Web.Module.Strings.Controller.CoordinatorResources", typeof(CoordinatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un autre coordonnateur utilise le même courriel. Veuillez en utiliser un autre..
        /// </summary>
        internal static string CoordinatorUseSameEmail {
            get {
                return ResourceManager.GetString("CoordinatorUseSameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour vers les options par défaut.
        /// </summary>
        internal static string DefaultSmtpOptions {
            get {
                return ResourceManager.GetString("DefaultSmtpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin doit être plus grande que la date de début.
        /// </summary>
        internal static string EndDateLowerThanStartDate {
            get {
                return ResourceManager.GetString("EndDateLowerThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un ou des fichiers ne peuvent pas être téléchargés.
        /// </summary>
        internal static string FilesCanNotBeDownload {
            get {
                return ResourceManager.GetString("FilesCanNotBeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder les nouvelles options.
        /// </summary>
        internal static string SaveNewSmtpOptions {
            get {
                return ResourceManager.GetString("SaveNewSmtpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début doit être égale ou plus grande à celle d&apos;aujourd&apos;hui.
        /// </summary>
        internal static string StartDateLowerThanNow {
            get {
                return ResourceManager.GetString("StartDateLowerThanNow", resourceCulture);
            }
        }
    }
}
